Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2023-07, with the labels that each got.

#137 CC-29960: Added missing mail sender.
  deploy.spryker-mpb2cintt.yml
Labels: bug

#138 CC-29918 Fixed AddressForm's city field input type.
  composer.json
  composer.lock
Labels: bug, ready-for-release

#140 CC-29931 Fixed displaying grand total of merchant order after refund
  composer.json
  composer.lock
Labels: bug, request-review

#141 CC-17241 Add config to not use merchant first and last name for conju…
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalConfig.php
Labels: bug, ready-for-release

#139 CC-29647 Fixed FE Yves commands.
  .prettierrc.js
  composer_back.json
  frontend/libs/command-line-parser.js
  frontend/libs/formatter.js
  frontend/merchant-portal/update-config-paths.js
  frontend/settings.js
  package-lock.json
  package.json
  tsconfig.mp.json
Labels: bug

#143 CC-24090: Fixed checkout address form on submit action.
  composer.json
  composer.lock
Labels: bug, request-review

#142 CC-30090 Adjust CORS configuration for demo shops GLUE APIs
  deploy.spryker-mpb2cintt.yml
Labels: ready-for-release

#144 CC-16486 Bugfixes integration
  composer.json
  composer.lock
  src/Pyz/Client/ProductReview/ProductReviewDependencyProvider.php
Labels: bug

#145 CC-30078 Fixed users search for agent
  composer.json
  composer.lock
Labels: bug

#148 CC-29892: Fixed payment methods in checkout data
  data/import/common/AT/payment_method_store.csv
  data/import/common/DE/payment_method_store.csv
  data/import/common/US/payment_method_store.csv
  data/import/common/common/payment_method.csv
  src/Pyz/Zed/CartsRestApi/CartsRestApiDependencyProvider.php
Labels: ready-for-release

#149 CC-16486 Fixed the self-link for the product review resource.
  composer.lock
  src/Pyz/Client/ProductReview/ProductReviewDependencyProvider.php
Labels: bug, ready-for-release

#154 FRW-2432 FRW-2377 Fixed Oauth token saving if it already exists. Fixed disabling CORS headers.
  composer.json
  composer.lock
Labels: bug

#151 CC-25992: Adjusted login mechanism for agent and customer.
  composer.lock
  src/Pyz/Yves/SecurityBlockerPage/SecurityBlockerPageConfig.php
Labels: bug
