Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2023-06, with the labels that each got.

#108 CC-25629 Updated Node.js to v18.
  .github/workflows/ci.yml
  .nvmrc
  composer.json
  deploy.aop-b2c-testing.yml
  deploy.aop-demoshop-b2c.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.spryker-b2c-eu.yml
  deploy.spryker-b2c-intt.yml
  deploy.spryker-b2c-intts.yml
  deploy.spryker-b2c-production.yml
  deploy.spryker-b2c-staging.yml
  deploy.spryker-b2c-us.yml
  deploy.spryker-b2csec.yml
  deploy.spryker-mpb2cintt.yml
  deploy.yml
  frontend/configs/development.js
  package-lock.json
  package.json
  tsconfig.yves.json
Labels: improvement

#74 CC-16903 Adjusted login mechanism for Backoffice and Merchant Portal.
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  src/Pyz/Client/SecurityBlocker/SecurityBlockerDependencyProvider.php
  src/Pyz/Zed/ErrorHandler/ErrorHandlerConfig.php
  src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
Labels: bug, ready-for-release

#109 CC-28473 Fixed date-picker validity dates.
  composer.lock
  package-lock.json
Labels: bug

#110 CC-23397: Added resource relationship support for Backend API.
  src/Pyz/Glue/DocumentationGeneratorApi/DocumentationGeneratorApiDependencyProvider.php
Labels: bug, request-review

#84 CC-25835: Fixed backoffice return creation.
  src/Pyz/Zed/SalesReturnGui/SalesReturnGuiDependencyProvider.php
Labels: bug, ready-for-release

#119 CC-29493 Added the robotframework-suite-tests repository to dependencies
  composer.json
  composer.lock
Labels: dependencies, request-review, improvement

#124 CC-29685: Adjusted installation configuration to fix an issue on AT store.
  config/install/docker.yml
Labels: bug, ready-for-release

#127 CC-21301: Fixed invalid checkout payment
  composer.json
  composer.lock
  src/Pyz/Zed/CartCode/CartCodeDependencyProvider.php
Labels: bug, ready-for-release

#130 CC-29900 Fixed refund for marketplace integration.
  src/Pyz/Zed/Refund/RefundDependencyProvider.php
Labels: bug, ready-for-release
