Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2023-11, with the labels that each got.

#222 CC-31727 Update npm dependencies
  composer.lock
  package-lock.json
Labels: bug, dependencies

#226 CC-31781 Added missing translation.
  data/import/common/common/glossary.csv
Labels: bug

#227 CC-31789 Cleaned up empty features
  composer.json
  composer.lock
Labels: ready-for-release

#230 CC-31786 Fixed preselected address state for multiple addresses at checkout
  composer.json
  composer.lock
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/address-item-form-field-list/address-item-form-field-list.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/multiple-shipment-toggler/index.ts
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/multiple-shipment-toggler/multiple-shipment-toggler.ts
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/multiple-shipment-toggler/multiple-shipment-toggler.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.ts
  src/Pyz/Yves/ShopUi/Theme/default/resources/form/form.twig
  tsconfig.yves.json
Labels: bug

#229 CC-31790 Updated navigation node demo data.
  data/import/common/common/navigation_node.csv
Labels: ready-for-release

#231 CC-31783: Adjusted service point selection after failed submit
  composer.json
  composer.lock
Labels: bug, ready-for-release

#234 CC-31765: Added missing plugin to check inactive product offer
  src/Pyz/Zed/Checkout/CheckoutDependencyProvider.php
Labels: bug

#235 FRW-6810 Fixed config file for DDE API
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: bug

#236 CC-31780 Fixed caching of categories in discounts.
  composer.json
  composer.lock
Labels: bug

#240 CC-31681 Integrated bugfixes
  composer.json
  composer.lock
Labels: bug, request-architecture-review

#239 CC-25879 Decreased memory usage in product data import.
  src/Pyz/Zed/DataImport/Business/DataImportBusinessFactory.php
  src/Pyz/Zed/DataImport/Business/Model/Product/Repository/ProductRepository.php
  src/Pyz/Zed/DataImport/Business/Model/Product/Repository/ProductRepositoryInterface.php
  src/Pyz/Zed/DataImport/Business/Model/ProductConcrete/ProductConcreteAttributesUniqueCheckStep.php
  src/Pyz/Zed/DataImport/DataImportConfig.php
Labels: bug

#241 CC-31771 Fixed product offer replacement
  .git.docker
  composer.json
  composer.lock
Labels: bug

#244 CC-31810 Fixed header dropdowns
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.scss
Labels: bug, ready-for-release

#237 CC-31547: Fixed get service point address collection request validation
  composer.json
  composer.lock
Labels: bug

#246 CC-25738 Fixed product offer prices API issue
  composer.json
  composer.lock
Labels: bug, ready-for-release

#233 CC-31600: Fixed warehouse user assignment validation
  composer.json
  composer.lock
Labels: bug

#247 CC-31859: Restrict access to BAPI endpoints for merchant users
  composer.json
  composer.lock
  src/Pyz/Glue/GlueBackendApiApplication/GlueBackendApiApplicationDependencyProvider.php
Labels: bug, ready-for-release

#253 Bulk bugfixes integration
  composer.json
  composer.lock
  tests/PyzTest/Glue/ProductConfigurations/RestApi/Fixtures/ProductConfigurationsRestApiFixtures.php
Labels: bug

#265 CC-26451: Password reset workflow improvements.
  composer.json
  composer.lock
Labels: bug
