Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2023-12, with the labels that each got.

#268 CC-32034 Fixed Robot package sync issue.
  .dockersyncignore
Labels: bug

#270 CC-31629 Fixed submit button disabling on the checkout address step.
  composer.lock
  src/Pyz/Yves/CheckoutPage/Theme/default/views/address/address.twig
  src/Pyz/Yves/ShopUi/Theme/default/resources/form/form.twig
Labels: bug

#275 CC-31983 Fixed Agent bar
  package-lock.json
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/agent-control-item/agent-control-item.scss
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/agent-control-item/agent-control-item.twig
  src/Pyz/Yves/AgentWidget/Theme/default/components/molecules/customer-list/customer-list.twig
  src/Pyz/Yves/AgentWidget/Theme/default/components/organisms/agent-control-bar/agent-control-bar.scss
  src/Pyz/Yves/AgentWidget/Theme/default/components/organisms/agent-control-bar/agent-control-bar.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/button/button.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/organisms/jumbotron-slider/jumbotron-slider.scss
  src/Pyz/Yves/ShopUi/Theme/default/styles/basics/_grid.scss
Labels: bug

#276 CC-32131 Fixed merchant portal and Product configurator build for CI acceptance configuration files.
  config/install/docker.ci.acceptance.robot.yml
  deploy.ci.acceptance.mariadb.robot.yml
Labels: bug

#273 CC-31773 Fixed issue with missing shipment price on Order Details page.
  src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/summary-sidebar/summary-sidebar.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/views/summary/summary.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail-table/order-detail-table.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/shipment-information/index.ts
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/shipment-information/shipment-information.scss
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/shipment-information/shipment-information.twig
  src/Pyz/Yves/CustomerReorderWidget/Theme/default/components/molecules/customer-reorder-form/customer-reorder-form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/action-bar/action-bar.scss
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: bug, ready-for-release

#278 CC-32150 Removed redundant services from robot deploy file.
  deploy.ci.acceptance.mariadb.robot.yml
Labels: ready-for-release, request-review, improvement

#279 CC-32149 Fixed logo displaying in Safari browser.
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/footer-logo/footer-logo.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/footer-logo/footer-logo.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/logo/logo.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/logo/logo.twig
Labels: bug

#281 CC-21163 Fixed ability to create return for bundle products.
  composer.lock
  src/Pyz/Yves/MerchantSalesReturnWidget/Theme/default/components/molecules/merchant-sales-return-create-form/merchant-sales-return-create-form.twig
  src/Pyz/Yves/MerchantSalesReturnWidget/Theme/default/components/molecules/separate-returns-by-merchant/separate-returns-by-merchant.ts
  src/Pyz/Yves/SalesReturnPage/Theme/default/components/molecules/return-create-form/return-create-form.twig
Labels: bug

#282 CC-32127 Cookies SameSite Lax integration.
  config/Shared/config_default.php
Labels: bug, ready-for-release

#284 CC-30070 Fixed table actions alignment.
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-table/order-table.twig
  src/Pyz/Yves/ProductAlternativeWidget/Theme/default/views/wishlist-product-alternative/wishlist-product-alternative.twig
  src/Pyz/Yves/SalesReturnPage/Theme/default/views/return-list/return-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/table/table.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/lazy-image/lazy-image.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/menu/menu.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/status/status.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/index.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.twig
  src/Pyz/Yves/WishlistPage/Theme/default/components/molecules/wishlist-detail-table/wishlist-detail-table.twig
  src/Pyz/Yves/WishlistPage/Theme/default/components/molecules/wishlist-overview-table/wishlist-overview-table.twig
Labels: bug

#285 CC-32217 Fixed Bundle items stock import data.
  data/import/common/common/product_stock.csv
Labels: bug, ready-for-release

#289 CC-18186 Fixed color selector on PDP.
  composer.lock
  src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-carousel/product-carousel.twig
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.twig
Labels: bug
