Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2023-03, with the labels that each got.

#49 CC-26175: Add robot tests
  .github/workflows/ci.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
Labels: enhancement, ready-for-release

#57 CC-25813: Tech Debt for AclMerchantPortal module.
  composer.json
  composer.lock
  src/Pyz/Zed/AclEntity/AclEntityDependencyProvider.php
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalDependencyProvider.php
  src/Pyz/Zed/Merchant/MerchantDependencyProvider.php
  src/Pyz/Zed/MerchantUser/MerchantUserDependencyProvider.php
Labels: ready-for-release, improvement

#55 CC-25744 Fixed missing number formatting on Sales page.
  src/Pyz/Yves/ExampleProductSalePage/Controller/SaleController.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageFactory.php
Labels: bug, request-review

#52 SUPESC-603 Fixed product category order overriding during data import
  src/Pyz/Zed/DataImport/Business/Model/ProductAbstract/ProductAbstractHydratorStep.php
Labels: bug

#54 CC-26185 CC-26347: Fixed scheduled prices concatenation for MariaDB.
  composer.lock
  config/install/docker.ci.acceptance.yml
Labels: bug, ready-for-release

#59 CC-21271 Unified unit tests with `@orchestrator/ngx-testing`.
  .github/workflows/ci.yml
  .stylelintrc.mp.js
  composer.json
  composer.lock
  frontend/merchant-portal/jest.config.ts
  frontend/merchant-portal/stylelint.js
  frontend/merchant-portal/tsconfig.spec.json
  frontend/merchant-portal/update-config-paths.js
  package-lock.json
  package.json
  tsconfig.base.json
  tsconfig.json
Labels: improvement

#60 SUPESC-618 Added customer access publisher trigger plugin
  composer.lock
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: bug, ready-for-release

#61 CC-25887 Updated `jquery` dependency version.
  composer.lock
  package-lock.json
  package.json
Labels: dependencies, ready-for-release, improvement

#58 SUPESC-610 Fixed date time displaying in merchant portal
  composer.lock
  src/Pyz/Zed/GuiTable/GuiTableConfig.php
Labels: bug, ready-for-release

#65 CC-25964 Fixed table features loading behavior.
  composer.json
  composer.lock
  package-lock.json
Labels: bug

#71 SUPESC-606 Fixed filtering by stores in Availability Notifications.
  composer.json
  composer.lock
  config/Shared/config_default.php
  deploy.aop-b2c-testing.yml
  deploy.aop-demoshop-b2c.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.yml
  deploy.spryker-b2c-eu.yml
  deploy.spryker-b2c-intt.yml
  deploy.spryker-b2c-intts.yml
  deploy.spryker-b2c-production.yml
  deploy.spryker-b2c-staging.yml
  deploy.spryker-b2c-us.yml
  deploy.spryker-b2csec.yml
  deploy.spryker-mpb2cintt.yml
  deploy.yml
Labels: bug, ready-for-release

#70 CC-25997 Lowered chunk size for search sync.
  config/Shared/config_default.php
Labels: bug, ready-for-release

#68 CC-23635 Added optimisations to handle product bundle on cart page.
  composer.json
  composer.lock
  src/Pyz/Zed/PriceCartConnector/PriceCartConnectorConfig.php
Labels: bug, ready-for-release

#66 SDK-1815 code cleanup
  composer.lock
  src/Pyz/Client/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Glue/Log/LogDependencyProvider.php
  src/Pyz/Service/Flysystem/FlysystemDependencyProvider.php
  src/Pyz/Yves/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
  src/Pyz/Yves/Log/LogDependencyProvider.php
  src/Pyz/Zed/DataImport/DataImportDependencyProvider.php
  src/Pyz/Zed/Flysystem/FlysystemDependencyProvider.php
Labels: improvement

#63 CC-16906 Adjusted session & token validation.
  composer.json
  composer.lock
  config/Zed/cronjobs/jenkins.php
  src/Orm/Zed/CustomerStorage/Persistence/SpyCustomerInvalidatedStorage.php
  src/Orm/Zed/CustomerStorage/Persistence/SpyCustomerInvalidatedStorageQuery.php
  src/Pyz/Client/Oauth/OauthDependencyProvider.php
  src/Pyz/Client/RabbitMq/RabbitMqConfig.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/Customer/Persistence/Propel/Schema/spy_customer.schema.xml
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Queue/QueueDependencyProvider.php
  src/Pyz/Zed/Synchronization/SynchronizationDependencyProvider.php
Labels: ready-for-release
