Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2023-04, with the labels that each got.

#76 CC-23529 Fixed ProductRelationCreateRelationCest test.
  tests/PyzTest/Zed/ProductRelation/Presentation/ProductRelationCreateRelationCest.php
  tests/PyzTest/Zed/ProductRelation/_support/PageObject/ProductRelationCreatePage.php
Labels: bug, ready-for-release

#73 CC-26329 Updated GitHub Actions to use Node.js 16.
  .github/workflows/ci.yml
Labels: improvement

#78 SUPESC-660 Updated `@spryker/oryx-for-zed` dependency version.
  composer.lock
  package-lock.json
  package.json
Labels: improvement

#77 CC-26405 Replaced `tslint` with `eslint` for YVES.
  .eslintrc.json
  .github/workflows/ci.yml
  .prettierignore
  composer.json
  frontend/libs/tslint.js
  package-lock.json
  package.json
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/autocomplete-form/autocomplete-form.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/breakpoint-dependent-block-placer/breakpoint-dependent-block-placer.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/nav-overlay/nav-overlay.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/node-animator/node-animator.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/scroll-parallax/scroll-parallax.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search-extended.ts
  tslint.json
Labels: ready-for-release

#81 CC-4006 Fixed exception when uploading files with File Manager.
  src/Pyz/Service/FileSystem/FileSystemDependencyProvider.php
Labels: bug, ready-for-release

#82 CC-26742 Fixed Robot CI configuration.
  .github/workflows/ci.yml
Labels: bug, ready-for-release

#85 CC-24114 Fixed 'print slip' different views.
  composer.json
  composer.lock
  package-lock.json
  src/Pyz/Yves/CheckoutPage/Theme/default/views/summary/summary.twig
  src/Pyz/Yves/SalesConfigurableBundleWidget/Theme/default/components/molecules/ordered-configured-bundle-product-secondary/ordered-configured-bundle-product-secondary.twig
  src/Pyz/Yves/SalesReturnPage/Theme/default/views/return-print/return-print.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/collapsible-list/collapsible-list.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/collapsible-list/collapsible-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/lazy-image/lazy-image.scss
Labels: bug
