Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2023-05, with the labels that each got.

#86 CC-15817 Added additional validation to form fields.
  composer.lock
  data/import/common/common/cms_block.csv
Labels: bug, ready-for-release

#94 CC-26834: added missing search plugins.
  src/Pyz/Client/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
Labels: ready-for-release

#100 CC-28283 Enabled runtime events for Backend API.
  src/Pyz/Glue/EventDispatcher/EventDispatcherDependencyProvider.php
  src/Pyz/Glue/GlueBackendApiApplication/GlueBackendApiApplicationDependencyProvider.php
Labels: bug, ready-for-release

#97 CC-17164 Fixed product offer availability when product offer is not assigned to a store.
  composer.json
  composer.lock
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: bug

#98 CC-28304 Updated Service Point Patch validation.
  config/install/ci.yml
  config/install/development.yml
  config/install/docker.ci.acceptance.yml
  config/install/docker.ci.api.yml
  config/install/docker.ci.functional.yml
  config/install/docker.yml
  config/install/testing.yml
Labels: bug, ready-for-release

#105 CC-26819 Fixed breadcrumbs for a product integration.
  composer.json
  composer.lock
  src/Pyz/Client/ProductCategoryStorage/ProductCategoryStorageDependencyProvider.php
  src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
Labels: bug, ready-for-release
