Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2023-10, with the labels that each got.

#182 SUPESC-783 Added missing integration for storing expenses in Quote.
  src/Pyz/Shared/PersistentCart/Transfer/persistent_cart.transfer.xml
  src/Pyz/Zed/Quote/QuoteConfig.php
Labels: bug, ready-for-release

#185 CC-31482 Update the oryx-for-zed dependency
  package-lock.json
  package.json
Labels: dependencies

#188 CC-29874 Updated `npm` dependencies.
  composer.lock
  package-lock.json
  package.json
Labels: dependencies

#186 CC-31029 Fixed exception for deactivated products in cart integration.
  composer.json
  composer.lock
  src/Pyz/Yves/CartPage/CartPageDependencyProvider.php
Labels: bug

#197 CC-31574 Update npm dependencies
  package-lock.json
Labels: dependencies

#202 CC-31636 Add missing image set relationship to concrete product.
  composer.json
  composer.lock
  src/Pyz/Glue/GlueBackendApiApplicationGlueJsonApiConventionConnector/GlueBackendApiApplicationGlueJsonApiConventionConnectorDependencyProvider.php
Labels: bug, ready-for-release

#191 FRW-6379: Synchronize cors-allow-origin property
  deploy.dev.yml
Labels: bug, ready-for-release

#210 FRW-6504 Adjusted Data Exchange API configuration file.
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: bug

#213 CC-31686 Docker CI fix integration.
  config/Shared/config_default-docker.ci.php
Labels: ready-for-release

#212 CC-31676 Updated tooling configuration for NPM evaluator.
  composer.lock
  tooling.yml
Labels: bug, ready-for-release
