Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2023-08, with the labels that each got.

#157 CC-30447: Integration CC-24108
  composer.json
  composer.lock
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Stock/Persistence/Propel/Schema/spy_stock.schema.xml
Labels: ready-for-release

#165 CC-29896 Introduced Docker container for Robot tests.
  .github/workflows/ci.yml
  .gitignore
  .robot/Dockerfile
  .robot/docker-compose.robot.yml
  composer.lock
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.dev.yml
Labels: ready-for-release, improvement

#166 CC-30403: Added merchant expander bulk plugins execution.
  composer.lock
  src/Pyz/Zed/Merchant/MerchantDependencyProvider.php
Labels: ready-for-release

#161 CC-20017 Fixed cart change item product image set.
  composer.json
  composer.lock
  src/Pyz/Zed/Cart/CartDependencyProvider.php
Labels: bug, ready-for-release

#167 CC-26235 Added extension validation for file upload.
  composer.json
  composer.lock
  data/import/common/common/mime_type.csv
  src/Pyz/Zed/FileManagerGui/FileManagerGuiConfig.php
  src/Pyz/Zed/PriceProductScheduleGui/PriceProductScheduleGuiConfig.php
  src/Pyz/Zed/ProductListGui/ProductListGuiConfig.php
Labels: bug, ready-for-release

#168 CC-31060 Update feature aliases
  composer.json
  composer.lock
Labels: bug, ready-for-release

#169 CC-31061 Fixed Postgres compatibility for push notification BAPI tests.
  composer.lock
Labels: bug, ready-for-release
