Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2024-12, with the labels that each got.

#475 FRW-9423 Fixed twig error for product view in Merchant Portal.
  .robot/Dockerfile
  composer.lock
Labels: robot-regression-ui-e2e

#474 ACP-4516: Integrated external search events
  composer.json
  composer.lock
  deploy.aop-b2c-testing.yml
  deploy.aop-demoshop-b2c.yml
  package-lock.json
  package.json
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig
  src/Pyz/Yves/CheckoutPage/Theme/default/templates/page-layout-order-submitted/page-layout-order-submitted.twig
  src/Pyz/Yves/EventDispatcher/EventDispatcherDependencyProvider.php
  src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
  src/Pyz/Yves/ProductSetDetailPage/Theme/default/views/set-detail/set-detail.twig
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.twig
  src/Pyz/Yves/Twig/TwigDependencyProvider.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/SearchHttp/Communication/SearchEndpointMessageTest.php
  tests/PyzTest/Zed/MessageBroker/_support/SearchHttpCommunicationTester.php
  tests/PyzTest/Zed/MessageBroker/codeception.yml
Labels: robot-regression-ui-e2e

#477 ACP-4455: Express checkout infrastructure integration.
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  src/Pyz/Glue/GlueApplication/GlueApplicationConfig.php
  src/Pyz/Glue/GlueApplication/GlueApplicationDependencyProvider.php
  src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-summary/cart-summary.twig
  src/Pyz/Yves/CheckoutPage/CheckoutPageConfig.php
  src/Pyz/Yves/CheckoutPage/CheckoutPageDependencyProvider.php
  src/Pyz/Yves/PaymentAppWidget/PaymentAppWidgetConfig.php
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Cart/CartDependencyProvider.php
  src/Pyz/Zed/Checkout/CheckoutDependencyProvider.php
  src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php
  src/Pyz/Zed/Payment/PaymentDependencyProvider.php
  src/Pyz/Zed/PaymentApp/PaymentAppDependencyProvider.php
  src/Pyz/Zed/PaymentAppShipment/PaymentAppShipmentConfig.php
  src/Pyz/Zed/PaymentCartConnector/PaymentCartConnectorConfig.php
Labels: robot-regression-ui-e2e

#473 CC-34874 Fixed Merchant Commission export
  src/Pyz/Service/DataExport/DataExportDependencyProvider.php
Labels: bug, ready-for-release, robot-regression-ui-e2e

#482 ACP-4615: Update of the modules.
  composer.lock
Labels: ready-for-release

#472 Integration: CC-20625
  composer.lock
  package-lock.json
Labels: bug, skip-robot-regression-ui-e2e

#457 FRW-8354 Create DMS acceptance tests.
  .github/workflows/ci.yml
  composer.lock
  package-lock.json
  tests/PyzTest/Zed/TestifyBackendApi/codeception.dynamic.fixtures.yml
Labels: improvement, skip-robot-regression-ui-e2e

#483 ACP-4516: Fix product data for algolia events
  src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
Labels: bug, ready-for-release, skip-robot-regression-ui-e2e

#476 FRW-7936 Integration.
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Yves/Router/RouterConfig.php
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/StorageRouter/StorageRouterConfig.php
  src/Pyz/Yves/StorageRouter/StorageRouterDependencyProvider.php
  src/SprykerConfig/CodeBucketConfig.php
  tests/PyzTest/Yves/Customer/_support/CustomerPresentationTester.php
Labels: improvement, robot-regression-ui-e2e

#489 SUPESC-859 Updated composer
  composer.lock
Labels: robot-regression-ui-e2e

#493 CC-14130: Fix memory leak on Backoffice ODP page with 100+ items.
  composer.lock
Labels: bug, request-review, skip-robot-regression-ui-e2e

#492 CC-34335: update webpack
  package-lock.json
  package.json
Labels: skip-robot-regression-ui-e2e

#496 CC-34976 Discount Improvements integration.
  composer.json
  composer.lock
  data/import/common/AT/discount_store.csv
  data/import/common/DE/discount_store.csv
  data/import/common/common/discount.csv
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: skip-robot-regression-ui-e2e, hackathon

#491 FRW-9299 Integrated Profiler enabling.
  composer.lock
  config/Shared/config_default-docker.dev.php
  config/Shared/config_default.php
  src/Pyz/Zed/MerchantPortalApplication/MerchantPortalApplicationDependencyProvider.php
  src/Pyz/Zed/SecurityMerchantPortalGui/SecurityMerchantPortalGuiConfig.php
Labels: skip-robot-regression-ui-e2e, hackathon

#488 FRW-9287 Added new twig var dumper plugin.
  composer.lock
  src/Pyz/Yves/Twig/TwigDependencyProvider.php
  src/Pyz/Zed/Twig/TwigDependencyProvider.php
Labels: skip-robot-regression-ui-e2e

#495 SUPESC-897 Improved performance of BundledProductTable.
  composer.lock
Labels: bug, skip-robot-regression-ui-e2e

#498 CC-35021: Updated cypress hash.
  composer.lock
  package-lock.json
Labels: bug, skip-robot-regression-ui-e2e

#497 FRW-9071 Integration.
  composer.lock
  data/import/common/common/glossary.csv
  src/Pyz/Glue/CustomersRestApi/Validation/customers.validation.yaml
  src/Pyz/Yves/CustomerPage/CustomerPageConfig.php
  src/Pyz/Zed/Customer/CustomerConfig.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerPasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRegistrationCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRestorePasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerUpdateCest.php
  tests/PyzTest/Yves/Customer/_support/PageObject/Customer.php
Labels: improvement, robot-regression-ui-e2e

#479 FRW-9013 Integration.
  composer.lock
  src/Pyz/Zed/Customer/CustomerConfig.php
Labels: robot-regression-ui-e2e

#480 FRW-9206 Improvement of artefact storage mechanism.
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: improvement, robot-regression-ui-e2e

#501 FRW-9641 Integration
  composer.lock
  src/Pyz/Glue/CustomersRestApi/Validation/customers.validation.yaml
  src/Pyz/Yves/ExampleProductSalePage/Controller/SaleController.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerPasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRegistrationCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerRestorePasswordCest.php
  tests/PyzTest/Glue/Customer/RestApi/CustomerUpdateCest.php
Labels: enhancement, robot-regression-ui-e2e

#506 FRW-9475 Fixed issue with new entity saving for DataExchangeAPI child relations.
  composer.lock
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: robot-regression-ui-e2e

#502 FRW-922 Upgraded predis library to version 2.3.0.
  composer.lock
Labels: improvement, robot-regression-ui-e2e

#504 ACP-4631: MessageBus observability improvement
  composer.json
  composer.lock
Labels: skip-robot-regression-ui-e2e
