Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2024-10, with the labels that each got.

#427 ACP-3661: Integrated the ACL entity synchronization command.
  composer.json
  composer.lock
  config/install/EU/production.yml
  config/install/US/production.yml
  config/install/production.dynamic-store.yml
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
Labels: robot-regression-ui-e2e

#420 FRW-8878 Integrated router performance issue fix.
  composer.lock
  src/Pyz/Zed/Router/RouterConfig.php
Labels: robot-regression-ui-e2e

#426 CC-34423 Product Concrete table in MP + Discount Rule based on customer order counter Integration
  composer.json
  composer.lock
  config/Zed/navigation-main-merchant-portal.xml
  data/import/common/AT/discount_store.csv
  data/import/common/DE/discount_store.csv
  data/import/common/US/discount_store.csv
  data/import/common/common/discount.csv
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: ready-for-release, improvement, robot-regression-ui-e2e

#433 FRW-9030 SUPESC Integrations
  composer.lock
Labels: robot-regression-ui-e2e

#434 FRW-7443 Store Context integration.
  composer.lock
  data/import/common/AT/store_context.csv
  data/import/common/DE/store_context.csv
  data/import/common/EU/store_context.csv
  data/import/common/US/store_context.csv
  data/import/common/commerce_setup_import_config_EU.yml
  data/import/common/commerce_setup_import_config_US.yml
  data/import/common/minimal.yml
  data/import/local/full_EU.yml
  data/import/local/full_US.yml
  data/import/production/full_EU.yml
  data/import/production/full_US.yml
  src/Pyz/Client/Store/StoreDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/DataImport/DataImportDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  src/Pyz/Zed/Store/StoreDependencyProvider.php
  src/Pyz/Zed/StoreContext/Persistence/Propel/Schema/spy_store_context.schema.xml
  src/Pyz/Zed/StoreGui/StoreGuiDependencyProvider.php
Labels: robot-regression-ui-e2e

#436 CC-34500 Adjusted merchant commission calculation to not rely on price mode per store configuration.
  composer.lock
  src/Pyz/Zed/MerchantCommission/MerchantCommissionConfig.php
Labels: request-review, improvement, robot-regression-ui-e2e

#438 FRW-9030 Integrations part 4
  composer.json
  composer.lock
Labels: robot-regression-ui-e2e

#435 FRW-8761 Adjusted configuration
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: skip-robot-regression-ui-e2e

#431 FRW-9030 Integrations part 1
  composer.lock
Labels: robot-regression-ui-e2e

#441 FRW-9164 Added extension point to the VariantTable.
  composer.lock
Labels: skip-robot-regression-ui-e2e

#444 FRW-9176 Integration.
  composer.lock
  src/Pyz/Zed/MerchantGui/MerchantGuiDependencyProvider.php
Labels: robot-regression-ui-e2e

#440 FRW-9030 Integrations part 5
  composer.lock
  src/Pyz/Zed/ProductStorage/Persistence/ProductStoragePersistenceFactory.php
Labels: robot-regression-ui-e2e

#442 FRW-1633 Integrations
  .git.docker
  composer.lock
Labels: robot-regression-ui-e2e

#448 CC-34672 Collapsible category tree integraton
  composer.json
  composer.lock
  package-lock.json
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig
  tsconfig.mp.json
Labels: ready-for-release, robot-regression-ui-e2e

#449 FRW-9170: integration
  composer.lock
Labels: robot-regression-ui-e2e

#445 Anallytics integration
  composer.json
  composer.lock
  config/Zed/navigation.xml
Labels: skip-robot-regression-ui-e2e

#450 FRW-6475 Fixed product label localized attributes for DS.
  composer.lock
  config/install/docker.ci.functional.yml
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: bug, robot-regression-ui-e2e

#455 CC-34707 Accessibility issue wrong color on State Machine button in Backoffice
  composer.json
  composer.lock
Labels: skip-robot-regression-ui-e2e

#451 Release 202410.0
  composer.json
  composer.lock
  config/install/docker.ci.functional.yml
  data/import/common/common/glossary.csv
  deploy.aop-b2c-testing.yml
  deploy.aop-demoshop-b2c.yml
  deploy.scos2-b2cmp.yml
  deploy.spryker-b2c-eu.yml
  deploy.spryker-b2c-intt.yml
  deploy.spryker-b2c-intts.yml
  deploy.spryker-b2c-production.yml
  deploy.spryker-b2c-staging.yml
  deploy.spryker-b2c-us.yml
  deploy.spryker-b2csec.yml
  deploy.spryker-mpb2cintt.yml
  deploy.spryker-scosb2cmp.yml
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
  tests/PyzTest/Yves/Application/Controller/HomepageCest.php
  tests/PyzTest/Yves/Application/_support/ApplicationControllerTester.php
  tests/PyzTest/Yves/Application/codeception.yml
  tests/PyzTest/Yves/Checkout/Process/Steps/SuccessStepTest.php
Labels: robot-regression-ui-e2e

#460 FRW-9241 Adjusted installation configs.
  config/install/ci.yml
  config/install/development.yml
  config/install/testing.yml
Labels: bug, robot-regression-ui-e2e

#461 CC-34246 Upgraded docker/sdk version.
  .git.docker
Labels: bug, skip-robot-regression-ui-e2e
