Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2024-08, with the labels that each got.

#396 ACP-2626: Stripe marketplace payment flow.
  composer.json
  composer.lock
  config/Shared/config_default.php
  config/Zed/navigation.xml
  data/import/common/common/glossary.csv
  package-lock.json
  public/MerchantPortal/redirect.php
  src/Orm/Zed/KernelApp/Persistence/SpyAppConfig.php
  src/Orm/Zed/KernelApp/Persistence/SpyAppConfigQuery.php
  src/Orm/Zed/MerchantApp/Persistence/SpyMerchantAppOnboarding.php
  src/Orm/Zed/MerchantApp/Persistence/SpyMerchantAppOnboardingQuery.php
  src/Orm/Zed/MerchantApp/Persistence/SpyMerchantAppOnboardingStatus.php
  src/Orm/Zed/MerchantApp/Persistence/SpyMerchantAppOnboardingStatusQuery.php
  src/Orm/Zed/SalesPaymentMerchant/Persistence/SpySalesPaymentMerchantPayout.php
  src/Orm/Zed/SalesPaymentMerchant/Persistence/SpySalesPaymentMerchantPayoutQuery.php
  src/Orm/Zed/SalesPaymentMerchant/Persistence/SpySalesPaymentMerchantPayoutReversal.php
  src/Orm/Zed/SalesPaymentMerchant/Persistence/SpySalesPaymentMerchantPayoutReversalQuery.php
  src/Pyz/Zed/Acl/AclConfig.php
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalDependencyProvider.php
  src/Pyz/Zed/KernelApp/KernelAppDependencyProvider.php
  src/Pyz/Zed/MessageBroker/MessageBrokerConfig.php
  src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php
  src/Pyz/Zed/Oms/OmsDependencyProvider.php
  src/Pyz/Zed/SalesPaymentMerchant/SalesPaymentMerchantDependencyProvider.php
  src/Pyz/Zed/SalesPaymentMerchantSalesMerchantCommission/SalesPaymentMerchantSalesMerchantCommissionConfig.php
  tsconfig.mp.json
Labels: robot-regression-ui-e2e

#399 ACP-3675: Update redirect.php
  public/MerchantPortal/redirect.php
Labels: skip-robot-regression-ui-e2e

#398 ACP-3589: Sales Payment details integration
  composer.json
  composer.lock
  config/Shared/config_default.php
  deploy.aop-demoshop-b2c.yml
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: skip-robot-regression-ui-e2e

#393 ACP-3544: Added MP
  deploy.aop-demoshop-b2c.yml
Labels: skip-robot-regression-ui-e2e

#402 ACP-3580: Payone ACP App: Klarna Payment Method
  composer.lock
  src/Pyz/Zed/Payment/PaymentConfig.php
Labels: ready-for-release, robot-regression-ui-e2e

#403 MP payment transfers with commission fixes for OMS (patches)
  composer.lock
Labels: skip-robot-regression-ui-e2e

#406 FRW-8868 Hackhaton CI.
  .github/workflows/ci.yml
Labels: skip-robot-regression-ui-e2e

#407 FRW-8932 Marketplace homepage fix integration.
  composer.lock
  src/Pyz/Zed/MerchantPortalApplication/Communication/MerchantPortalApplicationCommunicationFactory.php
  src/Pyz/Zed/MerchantPortalApplication/MerchantPortalApplicationConfig.php
Labels: skip-robot-regression-ui-e2e

#409 CC-34261 Split navigation for MP and BO.
  composer.lock
  config/Zed/navigation-main-merchant-portal.xml
  config/Zed/navigation-secondary-merchant-portal.xml
  config/Zed/navigation.xml
  src/Pyz/Zed/Twig/TwigDependencyProvider.php
  src/Pyz/Zed/ZedNavigation/ZedNavigationConfig.php
Labels: skip-robot-regression-ui-e2e
