Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2024-07, with the labels that each got.

#388 Enforce UI E2E Robot tests label for the PR to Master
  .github/workflows/enforce-labels.yml
Labels: skip-robot-regression-ui-e2e

#387 enforce e2e label
  .github/workflows/enforce-labels.yml
Labels: robot-regression-ui-e2e

#392 CC-33738 Audit logs integration into B2C MP Demoshop.
  composer.json
  composer.lock
  config/Shared/config_default.php
  src/Orm/Zed/StoreContext/Persistence/SpyStoreContext.php
  src/Orm/Zed/StoreContext/Persistence/SpyStoreContextQuery.php
  src/Pyz/Glue/Log/LogDependencyProvider.php
  src/Pyz/Yves/Log/LogDependencyProvider.php
  src/Pyz/Zed/Log/LogDependencyProvider.php
Labels: robot-regression-ui-e2e

#390 CC-31760 Integrate Merchant Commissions
  composer.json
  composer.lock
  config/Zed/navigation.xml
  config/Zed/oms/DummyPayment01.xml
  config/Zed/oms/DummySubprocess/DummyMarketplaceMerchantCommission01.xml
  config/Zed/oms/DummySubprocess/DummyMerchantCommission01.xml
  config/Zed/oms/MarketplacePayment01.xml
  data/import/common/AT/AT.yml
  data/import/common/AT/marketplace/merchant_commission_amount.csv
  data/import/common/AT/marketplace/merchant_commission_store.csv
  data/import/common/DE/DE.yml
  data/import/common/DE/marketplace/merchant_commission_amount.csv
  data/import/common/DE/marketplace/merchant_commission_store.csv
  data/import/common/US/US.yml
  data/import/common/US/marketplace/merchant_commission_amount.csv
  data/import/common/US/marketplace/merchant_commission_store.csv
  data/import/common/common/glossary.csv
  data/import/common/common/marketplace/merchant_commission.csv
  data/import/common/common/marketplace/merchant_commission_group.csv
  data/import/common/common/marketplace/merchant_commission_merchant.csv
  data/import/local/full_EU.yml
  data/import/local/full_US.yml
  data/import/production/full_EU.yml
  data/import/production/full_US.yml
  src/Orm/Zed/MerchantCommission/Persistence/SpyMerchantCommission.php
  src/Orm/Zed/MerchantCommission/Persistence/SpyMerchantCommissionAmount.php
  src/Orm/Zed/MerchantCommission/Persistence/SpyMerchantCommissionAmountQuery.php
  src/Orm/Zed/MerchantCommission/Persistence/SpyMerchantCommissionGroup.php
  src/Orm/Zed/MerchantCommission/Persistence/SpyMerchantCommissionGroupQuery.php
  src/Orm/Zed/MerchantCommission/Persistence/SpyMerchantCommissionMerchant.php
  src/Orm/Zed/MerchantCommission/Persistence/SpyMerchantCommissionMerchantQuery.php
  src/Orm/Zed/MerchantCommission/Persistence/SpyMerchantCommissionQuery.php
  src/Orm/Zed/MerchantCommission/Persistence/SpyMerchantCommissionStore.php
  src/Orm/Zed/MerchantCommission/Persistence/SpyMerchantCommissionStoreQuery.php
  src/Orm/Zed/SalesMerchantCommission/Persistence/SpySalesMerchantCommission.php
  src/Orm/Zed/SalesMerchantCommission/Persistence/SpySalesMerchantCommissionQuery.php
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalDependencyProvider.php
  src/Pyz/Zed/Calculation/CalculationDependencyProvider.php
  src/Pyz/Zed/Cart/CartDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/DataImport/DataImportDependencyProvider.php
  src/Pyz/Zed/MerchantCommission/MerchantCommissionConfig.php
  src/Pyz/Zed/MerchantCommission/MerchantCommissionDependencyProvider.php
  src/Pyz/Zed/MerchantCommissionGui/MerchantCommissionGuiDependencyProvider.php
  src/Pyz/Zed/MerchantSalesOrder/MerchantSalesOrderDependencyProvider.php
  src/Pyz/Zed/Oms/OmsDependencyProvider.php
  src/Pyz/Zed/Refund/RefundConfig.php
  src/Pyz/Zed/Refund/RefundDependencyProvider.php
  src/Pyz/Zed/RuleEngine/RuleEngineDependencyProvider.php
  src/Pyz/Zed/Sales/SalesConfig.php
  src/Pyz/Zed/Sales/SalesDependencyProvider.php
  src/Pyz/Zed/SalesMerchantCommission/SalesMerchantCommissionDependencyProvider.php
Labels: enhancement, request-review, robot-regression-ui-e2e

#394 Fixed issues with Commission integration.
  composer.json
  composer.lock
  package-lock.json
  tests/PyzTest/Zed/TestifyBackendApi/codeception.dynamic.fixtures.yml
Labels: bug, request-review, robot-regression-ui-e2e
