Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2024-06, with the labels that each got.

#378 FRW-8567 Integration
  composer.lock
  data/import/common/common/glossary.csv
  src/Pyz/Zed/DynamicEntity/data/installer/configuration.json
Labels: improvement, robot-regression-ui-e2e

#380 CC-33768: Added fixes for the "Robot Regression UI E2E"
  .github/workflows/robot-ui-e2e-tests.yml
Labels: improvement, robot-regression-ui-e2e

#382 CC-33794: Fix behavior while submit quantity on async cart
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.ts
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.twig
Labels: ready-for-release, robot-regression-ui-e2e

#381 Enabled cypress tests for epic - Async Cart reload feature.
  composer.lock
  package-lock.json
Labels: ready-for-release, robot-regression-ui-e2e

#383 CC-33728: Added Missing Demo Data for Merchant Special Opening Hours.
  .github/workflows/ci.yml
  composer.lock
  data/import/common/common/marketplace/merchant_opening_hours_date_schedule.csv
Labels: bug, ready-for-release
