Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2024-09, with the labels that each got.

#408 FRW-8938 Integration.
  composer.json
  composer.lock
  config/Shared/config_default.php
  src/Pyz/Service/Flysystem/FlysystemDependencyProvider.php
Labels: skip-robot-regression-ui-e2e, hackathon

#411 CC-34258: Multi-select attribute values (Fixathon)
  composer.lock
  data/import/common/common/product_abstract.csv
  data/import/common/common/product_attribute_key.csv
  data/import/common/common/product_management_attribute.csv
  src/Pyz/Glue/ProductsRestApi/ProductsRestApiDependencyProvider.php
  src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-detail-option/product-detail-option.twig
  src/Pyz/Zed/DataImport/Business/Model/ProductAbstract/ProductAbstractHydratorStep.php
  src/Pyz/Zed/ProductAttribute/ProductAttributeConfig.php
  src/Pyz/Zed/ProductAttribute/ProductAttributeDependencyProvider.php
Labels: request-review, robot-regression-ui-e2e

#412 CC-13685: Updated product quantity and total in Mini Cart Widget from catalog AJAX add-to-cart action.
  composer.lock
  src/Pyz/Yves/CartPage/CartPageConfig.php
  src/Pyz/Yves/CartPage/CartPageDependencyProvider.php
  src/Pyz/Yves/CartPage/CartPageFactory.php
  src/Pyz/Yves/CartPage/Plugin/Cart/CartBlockMiniCartViewExpanderPlugin.php
Labels: request-review, robot-regression-ui-e2e

#413 FRW-8766 Order matrix performance improvement integration.
  composer.lock
  config/Zed/cronjobs/jenkins.php
  config/Zed/navigation.xml
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
Labels: skip-robot-regression-ui-e2e

#414 ACP-3558 Merchant payment expense support.
  composer.lock
  config/Shared/config_default-docker.dev.php
  src/Pyz/Zed/SalesPaymentMerchant/SalesPaymentMerchantConfig.php
Labels: ready-for-release, robot-regression-ui-e2e

#415 ACP-3824: updated composer, Added acl plugin
  composer.lock
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalDependencyProvider.php
Labels: robot-regression-ui-e2e

#416 Fixed the Queue Worker stopping too early when using a "stop-when-empty" option.
  composer.lock
  src/Pyz/Zed/Queue/QueueDependencyProvider.php
Labels: bug, skip-robot-regression-ui-e2e

#417 CC-33982: P&S optimisation.
  composer.lock
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/CustomerAccessStorage/Persistence/Propel/Schema/spy_unauthenticated_customer_access_storage.schema.xml
  src/Pyz/Zed/Event/EventConfig.php
  src/Pyz/Zed/SynchronizationBehavior/SynchronizationBehaviorConfig.php
  src/Pyz/Zed/TaxProductStorage/Persistence/Propel/Schema/spy_tax_product_storage.schema.xml
Labels: request-review, robot-regression-ui-e2e

#418 FRW-7903 Integration
  composer.lock
  src/Pyz/Zed/Product/ProductConfig.php
Labels: bug, skip-robot-regression-ui-e2e

#421 CC-26445 Integration
  src/Pyz/Yves/CustomerPage/CustomerPageConfig.php
Labels: bug, skip-robot-regression-ui-e2e

#423 FRW-8801 Added PHP 8.3 support.
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
  .scrutinizer.yml
  README.md
  composer.json
  composer.lock
  deploy.ci.acceptance.dynamic-store.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store.yml
  deploy.ci.api.mariadb.dynamic-store.robot.yml
  deploy.ci.api.mariadb.dynamic-store.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store.yml
  deploy.ci.functional.mariadb.dynamic-store.yml
  deploy.ci.functional.mariadb.prefer-lowest.dynamic-store.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store.yml
  deploy.dev.yml
  deploy.dynamic-store.yml
  deploy.scos2-b2cmp.yml
  deploy.spryker-b2c-eu.yml
  deploy.spryker-b2c-intt.yml
  deploy.spryker-b2c-intts.yml
  deploy.spryker-b2c-production.yml
  deploy.spryker-b2c-staging.yml
  deploy.spryker-b2c-us.yml
  deploy.spryker-b2csec.yml
  deploy.spryker-mpb2cintt.yml
  deploy.spryker-scosb2cmp.yml
  deploy.yml
  phpcs.xml
  src/Pyz/Yves/EventDispatcher/EventDispatcherDependencyProvider.php
Labels: improvement, robot-regression-ui-e2e
