Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2025-07, with the labels that each got.

#594 OPS-4941 Updated RabbitMQ version.
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.acceptance.mariadb.robot.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store-off.yml
  deploy.ci.api.mariadb.dynamic-store-off.yml
  deploy.ci.api.mariadb.robot.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store-off.yml
  deploy.ci.functional.mariadb.dynamic-store-off.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store-off.yml
  deploy.dev.yml
  deploy.dynamic-store-off.yml
  deploy.yml
Labels: improvement, run-latest-ci, run-api-ci, run-functional-ci, run-static-ci, run-ui-ci

#595 FRW-901 Integrations.
  composer.lock
Labels: bug, run-latest-ci, run-ui-ci

#598 FRW-10501: Integration.
  composer.lock
Labels: run-latest-ci, run-ui-ci

#607 FRW-10720 Updated dependencies
  composer.json
  composer.lock
  src/Pyz/Zed/Application/ApplicationDependencyProvider.php
  src/Pyz/Zed/Twig/TwigDependencyProvider.php
  tests/PyzTest/Yves/Checkout/Process/Steps/SummaryStepTest.php
  tests/PyzTest/Zed/AclEntity/Persistence/AclDirector/AclQueryDirectorTest.php
  tests/PyzTest/Zed/AclEntity/Persistence/AclDirector/DefaultAclQueryScopeTest.php
  tests/PyzTest/Zed/AclEntity/Persistence/AclDirector/InheritedAclQueryScopeTest.php
  tests/PyzTest/Zed/AclEntity/_support/AclQueryDirectorTester.php
  tests/PyzTest/Zed/Console/_data/cli_sandbox/config/Shared/config_default.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCaptureFailedMessageCest.php
  tests/PyzTest/Zed/MessageBroker/MessageHandlers/Payment/Presentation/PaymentCapturedMessageCest.php
Labels: improvement, run-latest-ci, run-api-ci, run-compatibility-ci, run-functional-ci, run-static-ci, run-ui-ci, run-npm-ci

#611 FRW-10741 Agent MFA integration.
  composer.lock
  src/Pyz/Yves/AgentPage/Theme/default/components/molecules/agent-navigation/agent-navigation.twig
  src/Pyz/Yves/AgentPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/user-set-up-page/set-up-page.twig
Labels: improvement, run-ui-ci

#620 FRW-10759 Integrations and fixes.
  composer.json
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/glossary.csv
  src/Pyz/Yves/AgentPage/Theme/default/views/login/login.twig
  src/Pyz/Yves/CustomerPage/Theme/default/templates/page-layout-login/page-layout-login.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/customer-set-up-page/customer-set-up-page.twig
  src/Pyz/Yves/MultiFactorAuth/Theme/default/views/user-set-up-page/user-set-up-page.twig
  src/Pyz/Zed/Transfer/TransferConfig.php
Labels: bug, dependencies, run-latest-ci, run-functional-ci, run-static-ci, run-ui-ci

#623 CC-36096: Fixes security issue with node modules
  package-lock.json
Labels: run-static-ci, run-npm-ci

#626 CC-36086 OA. Yves. Order Total is not updated in the Order History table
  composer.json
  composer.lock
Labels: bug, run-latest-ci, run-ui-ci

#624 FRW-10772 Fixed navigation from homepage.
  src/Pyz/Shared/CmsBlock/Theme/default/template/type_1_inspirational_block.twig
  src/Pyz/Shared/CmsBlock/Theme/default/template/type_2_inspirational_block.twig
  src/Pyz/Yves/ContentBannerWidget/Theme/default/components/molecules/banner-jumbotron/banner-jumbotron.twig
Labels: bug, run-latest-ci, run-api-ci, run-compatibility-ci, run-functional-ci, run-ui-ci

#627 FRW-10776 Integration.
  composer.lock
Labels: bug, run-ui-ci

#618 FRW-10736 Integration.
  src/Pyz/Shared/CmsBlock/Theme/default/template/type_1_inspirational_block.twig
  src/Pyz/Shared/CmsBlock/Theme/default/template/type_2_inspirational_block.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/category-card/category-card.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/category-list-item/category-list-item.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-links-list/suggestion-links-list.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/suggestion-product/suggestion-product.twig
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/view-mode-switch/view-mode-switch.twig
  src/Pyz/Yves/CmsSearchPage/Theme/default/components/molecules/search-cms-results/search-cms-results.twig
  src/Pyz/Yves/ContentBannerWidget/Theme/default/components/molecules/banner-jumbotron/banner-jumbotron.twig
  src/Pyz/Yves/ContentProductWidget/Theme/default/views/cms-product-abstract-list-alternative/cms-product-abstract-list-alternative.twig
  src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/customer-form/customer-form.twig
  src/Pyz/Yves/DiscountPromotionWidget/Theme/default/views/cart-discount-promotion-products-list/cart-discount-promotion-products-list.twig
  src/Pyz/Yves/MerchantProductOfferWidget/Theme/default/components/molecules/merchant-product-offer-item/merchant-product-offer-item.twig
  src/Pyz/Yves/MerchantProductWidget/Theme/default/components/molecules/merchant-product-item/merchant-product-item.twig
  src/Pyz/Yves/MerchantWidget/Theme/default/components/molecules/sold-by-merchant/sold-by-merchant.twig
  src/Pyz/Yves/ProductAlternativeWidget/Theme/default/views/wishlist-product-alternative/wishlist-product-alternative.twig
  src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-configurator/product-configurator.twig
  src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
  src/Pyz/Yves/ProductGroupWidget/Theme/default/components/molecules/color-selector-pdp/color-selector-pdp.twig
  src/Pyz/Yves/ProductSetListPage/Theme/default/views/set-list/set-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/banner/banner.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/form/form.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-icon-list/navigation-icon-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-list/navigation-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/navigation-multilevel-node/navigation-multilevel-node.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card-item/product-card-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-card/product-card.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item-list/product-item-list.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-item/product-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/product-list-item/product-list-item.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.twig
  src/Pyz/Yves/WishlistPage/Theme/default/components/molecules/wishlist-detail-table/wishlist-detail-table.twig
Labels: bug, run-latest-ci, run-api-ci, run-compatibility-ci, run-functional-ci, run-static-ci, run-ui-ci

#629 FRW-10760 Fixed 404 error on filter by category in dynamic sale category
  src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig
Labels: bug, run-latest-ci, run-ui-ci

#631 FRW-10781 Fixed banner link to the Spryker website
  data/import/common/common/cms_block.csv
  data/import/common/common/glossary.csv
Labels: bug, run-latest-ci, run-ui-ci
