Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2025-04, with the labels that each got.

#547 CC-22722: Order Sequence Generation integration
  composer.lock
  src/Pyz/Zed/Sales/SalesConfig.php
Labels: improvement, run-latest-ci, run-functional-ci, run-ui-ci

#553 CC-26244: [Performance] Quote is validated twice in Yves CartController
  composer.lock
  src/Pyz/Yves/CartPage/CartPageConfig.php
Labels: bug, run-static-ci, run-ui-ci

#557 CC-34245 bootstrap upgrade integration
  composer.lock
  package-lock.json
  package.json
Labels: run-latest-ci

#556 CC-35490 Fixed flaky CMS page test
  tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiCreatePageCest.php
  tests/PyzTest/Zed/CmsGui/_support/CmsGuiPresentationTester.php
Labels: bug, run-compatibility-ci, run-static-ci
