Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2025-06, with the labels that each got.

#581 CC-35703 Discount Improvements (Customer Reference).
  composer.json
  composer.lock
  data/import/common/AT/discount_store.csv
  data/import/common/DE/discount_store.csv
  data/import/common/US/discount_store.csv
  data/import/common/common/discount.csv
  data/import/common/common/discount_voucher.csv
  src/Orm/Zed/CustomerDiscountConnector/Persistence/SpyCustomerDiscount.php
  src/Orm/Zed/CustomerDiscountConnector/Persistence/SpyCustomerDiscountQuery.php
  src/Orm/Zed/PaymentApp/Persistence/SpyPaymentAppPaymentStatus.php
  src/Orm/Zed/PaymentApp/Persistence/SpyPaymentAppPaymentStatusHistory.php
  src/Orm/Zed/PaymentApp/Persistence/SpyPaymentAppPaymentStatusHistoryQuery.php
  src/Orm/Zed/PaymentApp/Persistence/SpyPaymentAppPaymentStatusQuery.php
  src/Pyz/Zed/Checkout/CheckoutDependencyProvider.php
  src/Pyz/Zed/Discount/DiscountDependencyProvider.php
Labels: run-latest-ci

#582 CC-35253: Update Angular to 18
  composer.lock
  package-lock.json
  package.json
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.scss
  src/Pyz/Yves/ShopUi/Theme/default/components/molecules/slick-carousel/slick-carousel.scss
Labels: run-latest-ci

#586 ACP-5071: integrated translation for Vertex validation
  composer.json
  composer.lock
  data/import/common/common/glossary.csv
Labels: run-api-ci, run-functional-ci

#587 Fixed failed cypress tests.
  composer.lock
  package-lock.json
Labels: run-ui-ci

#588 Enabled composer cache for CI jobs.
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
  deploy.ci.acceptance.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.acceptance.mariadb.robot.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store-off.yml
  deploy.ci.api.mariadb.dynamic-store-off.yml
  deploy.ci.api.mariadb.robot.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store-off.yml
  deploy.ci.functional.mariadb.dynamic-store-off.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
Labels: run-latest-ci, run-compatibility-ci

#589 Integration: SUPESC-977
  composer.lock
Labels: bug, run-latest-ci

#593 CC-35578: Fixed Gift Card email templates.
  composer.lock
  package-lock.json
Labels: run-compatibility-ci, run-ui-ci
