Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2025-03, with the labels that each got.

#531 [All demoshops] Red cypress tests
  composer.lock
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  package-lock.json
Labels: run-ui-ci

#535 ACP-4150: Added missing PHPDoc description
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: run-static-ci

#534 FRW-10067 Added CustomerEmailChangeRequestWidget widget
  src/Pyz/Yves/CustomerPage/Theme/default/views/profile/profile.twig
Labels: bug, run-latest-ci

#533 CC-34127 Added CSRF param to Company Role User form.
  composer.lock
  package-lock.json
Labels: run-latest-ci

#540 FRW-9988: integration
  composer.lock
Labels: run-static-ci

#545 FRW-9983 Integration
  composer.lock
  config/Shared/config_default.php
  data/import/common/common/cms_block.csv
  data/import/common/common/glossary.csv
  tests/PyzTest/Yves/Customer/Presentation/CustomerProfileCest.php
  tests/PyzTest/Yves/Customer/_support/PageObject/CustomerProfilePage.php
Labels: run-latest-ci, run-static-ci, run-npm-ci
