Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2025-05, with the labels that each got.

#560 Update Jenkins version to 2.493.2
  deploy.aop-b2c-testing.yml
  deploy.aop-demoshop-b2c.yml
  deploy.aws-env-template.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.dev.dynamic-store-off.yml
  deploy.dev.yml
  deploy.dynamic-store-off.yml
  deploy.scos2-b2cmp.yml
  deploy.spryker-b2c-eu.yml
  deploy.spryker-b2c-intt.yml
  deploy.spryker-b2c-intts.yml
  deploy.spryker-b2c-production.yml
  deploy.spryker-b2c-staging.yml
  deploy.spryker-b2c-us.yml
  deploy.spryker-b2csec.yml
  deploy.spryker-mpb2cintt.yml
  deploy.spryker-scosb2cmp.yml
  deploy.yml
Labels: run-latest-ci

#563 CC-35650 April 2025 integrations.
  composer.lock
  tests/PyzTest/Yves/Checkout/Process/Steps/ShipmentStepTest.php
Labels: run-latest-ci, run-static-ci, run-npm-ci

#570 FRW-10406 Integration.
  composer.json
  composer.lock
  config/Shared/config_default.php
  config/Zed/cronjobs/jenkins.php
  src/Pyz/Yves/Router/RouterDependencyProvider.php
  src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/Sitemap/SitemapDependencyProvider.php
Labels: improvement, run-functional-ci, run-static-ci

#571 CC-35509: remove weekly CI
  .github/actions/job-slack-notifications/action.yml
  .github/actions/scheduled-job-slack-notifications/action.yml
  .github/workflows/ci.yml
  .github/workflows/robot-ui-e2e-tests.yml
Labels: run-latest-ci, run-compatibility-ci

#574 CC-35509 Remove label check at static validation ci job.
  .github/workflows/ci.yml
Labels: run-latest-ci, run-compatibility-ci

#575 SUPESC-899 svg sprite asset generation integration
  .gitignore
  composer.lock
  frontend/configs/development.js
  frontend/libs/icon-sprite-extractor.js
  frontend/settings.js
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon-sprite/icon-sprite.twig
  src/Pyz/Yves/ShopUi/Theme/default/components/atoms/icon/icon.twig
Labels: run-latest-ci

#568 CC-35103 Added Apply Scheduled Price and P&S into destructive deployment.
  config/install/destructive.yml
Labels: bug, run-ui-ci
