Repository spryker-shop/b2c-demo-marketplace, pull requests merged in 2025-08, with the labels that each got.

#642 CC-36115 Integrated bugfixes.
  composer.lock
Labels: run-latest-ci

#637 FRW-10805 OTEL Integration
  .git.docker
  .github/workflows/ci.yml
  composer.json
  composer.lock
  config/Shared/config_default.php
  config/Zed/navigation-secondary-merchant-portal.xml
  config/install/docker.yml
  deploy.aws-env-template.yml
  deploy.ci.acceptance.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
  deploy.ci.acceptance.mariadb.dynamic-store-off.yml
  deploy.ci.acceptance.mariadb.prefer-lowest.yml
  deploy.ci.acceptance.mariadb.robot.yml
  deploy.ci.acceptance.mariadb.yml
  deploy.ci.acceptance.yml
  deploy.ci.api.dynamic-store-off.yml
  deploy.ci.api.mariadb.dynamic-store-off.yml
  deploy.ci.api.mariadb.robot.yml
  deploy.ci.api.mariadb.yml
  deploy.ci.api.yml
  deploy.ci.functional.dynamic-store-off.yml
  deploy.ci.functional.mariadb.dynamic-store-off.yml
  deploy.ci.functional.mariadb.prefer-lowest.yml
  deploy.ci.functional.mariadb.yml
  deploy.ci.functional.yml
  deploy.dev.dynamic-store-off.yml
  deploy.dev.yml
  deploy.dynamic-store-off.yml
  deploy.yml
  package-lock.json
  src/Pyz/Service/Monitoring/MonitoringDependencyProvider.php
  src/Pyz/Zed/AclMerchantPortal/AclMerchantPortalDependencyProvider.php
  src/Pyz/Zed/AgentSecurityMerchantPortalGui/AgentSecurityMerchantPortalGuiConfig.php
  src/Pyz/Zed/AgentSecurityMerchantPortalGui/AgentSecurityMerchantPortalGuiDependencyProvider.php
  src/Pyz/Zed/Console/ConsoleDependencyProvider.php
  src/Pyz/Zed/MultiFactorAuth/MultiFactorAuthDependencyProvider.php
  src/Pyz/Zed/MultiFactorAuthMerchantPortal/MultiFactorAuthMerchantPortalDependencyProvider.php
  src/Pyz/Zed/SecurityMerchantPortalGui/SecurityMerchantPortalGuiConfig.php
  src/Pyz/Zed/SecurityMerchantPortalGui/SecurityMerchantPortalGuiDependencyProvider.php
  src/Pyz/Zed/ZedNavigation/ZedNavigationDependencyProvider.php
  tsconfig.mp.json
Labels: improvement, run-latest-ci, run-api-ci, run-compatibility-ci, run-functional-ci, run-static-ci, run-ui-ci, run-npm-ci

#658 CC-35423: Text alternatives integration
  composer.lock
  data/import/common/common/product_image.csv
  data/import/common/common/product_set.csv
  src/Pyz/Shared/ProductImage/ProductImageConfig.php
  src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.twig
  src/Pyz/Yves/ProductSetListPage/Theme/default/views/set-list/set-list.twig
  src/Pyz/Yves/ProductSetWidget/Theme/default/components/organisms/product-set-details/product-set-details.twig
  src/Pyz/Zed/DataImport/Business/DataImportBusinessFactory.php
  src/Pyz/Zed/DataImport/Business/Model/ProductImage/Writer/ProductImagePropelDataSetWriter.php
  src/Pyz/Zed/DataImport/Business/Model/ProductSet/ProductSetImageExtractorStep.php
  src/Pyz/Zed/DataImport/Business/Model/ProductSet/ProductSetImageLocalizedAttributesExtractorStep.php
  src/Pyz/Zed/DataImport/Business/Model/ProductSet/ProductSetWriterStep.php
  src/Pyz/Zed/ProductPageSearch/ProductPageSearchDependencyProvider.php
Labels: run-functional-ci, run-static-ci, run-ui-ci

#664 SUPESC-996 Integration.
  src/Pyz/Glue/Log/LogDependencyProvider.php
  src/Pyz/Yves/Log/LogDependencyProvider.php
  src/Pyz/Zed/Log/LogDependencyProvider.php
Labels: bug, run-functional-ci

#663 ACP-5354: Algolia: global search to CMS and docs integration
  composer.lock
  config/Shared/config_default.php
  config/Zed/cronjobs/jenkins.php
  src/Pyz/Client/Catalog/CatalogDependencyProvider.php
  src/Pyz/Client/CmsPageSearch/CmsPageSearchDependencyProvider.php
  src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php
  src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
Labels: run-functional-ci, run-static-ci, run-ui-ci

#662 FRW-10554 Reduce the number of CI jobs
  .github/workflows/ci.yml
  deploy.ci.acceptance.postgres.dynamic-store-off.cypress.yml
Labels: run-latest-ci, run-api-ci, run-compatibility-ci, run-functional-ci, run-static-ci, run-ui-ci, run-npm-ci
